### ISSUE TITLE
Unable to delete record.

### ISSUE THREAD

**Issue by sheetalkumar105** [ashokvishwakarma/dgraph-orm#1]
I am getting error on delete:

    { Error: 2 UNKNOWN: uid must be present and non-zero while deleting edges.
    at Object.exports.createStatusError (/Users/sheetalkumar/WebRoot/ok-dgraph/node_modules/grpc/src/common.js:91:15)
    at Object.onReceiveStatus (/Users/sheetalkumar/WebRoot/ok-dgraph/node_modules/grpc/src/client_interceptors.js:1204:28)
    at InterceptingListener._callNext (/Users/sheetalkumar/WebRoot/ok-dgraph/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/Users/sheetalkumar/WebRoot/ok-dgraph/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/Users/sheetalkumar/WebRoot/ok-dgraph/node_modules/grpc/src/client_interceptors.js:845:24)
  code: 2,
  metadata: Metadata { _internal_repr: {} },
  details: 'uid must be present and non-zero while deleting edges.' }

**Comment by ashokvishwakarma** [comment]
Fixed in V1.0.9, hence closing.
