### ISSUE TITLE
Model.delete() not working!

### ISSUE THREAD

**Issue by PraveenKumarPalai** [ashokvishwakarma/dgraph-orm#13]
When using _Model.delete()_..
I am getting the following **error message**.

// Delete edges and values of single model
```Model.delete('0x1');```

**Error: device has no attribute 0
    at Model._check_attributes (/Users/praveenkumarpalai/WebRoot/hiilife-backend/node_modules/dgraph-orm/src/model.ts:733:15)
    at Model.<anonymous> (/Users/praveenkumarpalai/WebRoot/hiilife-backend/node_modules/dgraph-orm/src/model.ts:552:10)
    at step (/Users/praveenkumarpalai/WebRoot/hiilife-backend/node_modules/dgraph-orm/lib/model.js:39:23)
    at Object.next (/Users/praveenkumarpalai/WebRoot/hiilife-backend/node_modules/dgraph-orm/lib/model.js:20:53)**

-----------------
// Delete edges and values of mutliple model
```Model.delete(['0x1']);```

**Error: device has no attribute 0x1
    at Model._check_attributes (/Users/praveenkumarpalai/WebRoot/hiilife-backend/node_modules/dgraph-orm/src/model.ts:733:15)
    at Model.<anonymous> (/Users/praveenkumarpalai/WebRoot/hiilife-backend/node_modules/dgraph-orm/src/model.ts:552:10)
    at step (/Users/praveenkumarpalai/WebRoot/hiilife-backend/node_modules/dgraph-orm/lib/model.js:39:23)
    at Object.next (/Users/praveenkumarpalai/WebRoot/hiilife-backend/node_modules/dgraph-orm/lib/model.js:20:53)**

-------------

**Comment by ashokvishwakarma** [comment]
Fixed in 1.2.2

**Comment by PraveenKumarPalai** [comment]
Cool!
