### ISSUE TITLE
Error after create new record.

### ISSUE THREAD

**Issue by sheetalkumar105** [ashokvishwakarma/dgraph-orm#2]
Error: Transaction has already been committed or discarded
    at Object.<anonymous> (/Users/sheetalkumar/WebRoot/ok-dgraph/node_modules/dgraph-js/lib/errors.js:4:24)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Module._compile (/Users/sheetalkumar/WebRoot/ok-dgraph/node_modules/pirates/lib/index.js:83:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Object.newLoader [as .js] (/Users/sheetalkumar/WebRoot/ok-dgraph/node_modules/pirates/lib/index.js:88:7)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:22:18)

**Comment by ashokvishwakarma** [comment]
Fixed in V1.1.0, hence closing.
